
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "futu-opend.fullname" . }}-credentials
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
