apiVersion: v1
kind: Pod
metadata:
  name: {{ include "futu-opend.fullname" . }}
  labels:
    {{- include "futu-opend.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ include "futu-opend.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: '{{ include "futu-opend.fullname" . }}'
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      stdin: true
      tty: true
      env:
        - name: FUTU_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "futu-opend.fullname" . }}-credentials
              key: futu-account-id
        - name: FUTU_ACCOUNT_PWD
          valueFrom:
            secretKeyRef:
              name: {{ include "futu-opend.fullname" . }}-credentials
              key: futu-account-pwd
        - name: FUTU_OPEND_IP
          value: 0.0.0.0
        - name: FUTU_OPEND_PORT
          value: "{{ .Values.service.port }}"
      ports:
        - name: opend
          containerPort: {{ .Values.service.port }}
          protocol: TCP
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      volumeMounts:
        - name: futu-opend-rsa
          mountPath: /.futu
          readOnly: true
        - name: futu-opend-pv
          mountPath: /root/.com.futunn.FutuOpenD
      readinessProbe:
        tcpSocket:
          port: {{ .Values.service.port }}
        initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      livenessProbe:
        tcpSocket:
          port: {{ .Values.service.port }}
        initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
        periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  volumes:
    - name: futu-opend-rsa
      secret:
        secretName: {{ include "futu-opend.fullname" . }}-rsa
    - name: futu-opend-pv
      persistentVolumeClaim:
        claimName: futu-opend-pvc
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
